// const keywordsArr = ['aj1',
// 'aj',
// '李宁',
// '匡威',
// '空军一号',
// 'nike',
// '欧文4',
// 'aj11',
// 'vans',
// 'boost',
// '阿迪达斯',
// 'aj13',
// '拖鞋',
// '耐克',
// '科比',
// 'aj3',
// 'aj4',
// '双肩包',
// '詹姆斯',
// '彪马',
// 'puma',
// '袜子',
// 'aj32',
// '李宁 篮球鞋',
// 'adidas',
// '匡威1970s',
// '卡西欧',
// 'Nike',
// 'off white',
// 'champion',
// '篮球鞋',
// '欧文',
// '欧文3',
// 'air max',
// 'af1',
// '篮球',
// 'aj6',
// '万斯',
// 'aj5',
// '卫衣',
// '哈登',
// '短裤',
// '喷泡',
// '冠军',
// '椰子',
// '手表',
// '安踏',
// '耐克篮球鞋',
// '詹姆斯15',
// '书包',
// 'yeezy',
// 'hd2017',
// 'aj12',
// 'eqt',
// 'pg2',
// 'AJ',
// 'supreme',
// '华莱士',
// '球衣',
// '悟道',
// '回力',
// 'kobe',
// 'aj7',
// '亚瑟士',
// 'Adidas',
// '罗斯',
// '利拉德4',
// '拖鞋 男',
// 'air',
// '耳机',
// '李宁篮球鞋',
// 'nmd',
// 'aj31',
// '阿迪达斯 鞋',
// 'kd11',
// '空军一号 耐克',
// '新百伦',
// '皮蓬',
// '工装裤',
// '三叶草',
// 'kd10',
// 'nike air max',
// '韦德之道',
// 'nike sb',
// 'T恤',
// 'ultra boost',
// 'air force 1',
// 'jordan',
// '运动裤',
// '板鞋',
// '椰子 yeezy',
// '卡西欧 手表',
// '锐步',
// '利拉德',
// '短袖',
// '女',
// 'aj拖鞋',
// '卫衣 男',
// 'kd',
// '韦德',
// 'nike air',
// '背心',
// '阿迪达斯外套',
// 'hyperdunk',
// '安德玛',
// 'zoom',
// '包',
// 'AJ1',
// '哈登2',
// 'pg1',
// '斐乐',
// '裤子',
// '老爹鞋',
// '耐克 鞋',
// '喷',
// 'converse',
// '罗斯9',
// 'air jordan',
// 'hd',
// 'pg2.5',
// 'vapormax',
// '万斯 vans',
// 'stussy',
// '鬼冢虎',
// 'aape',
// '椰子350',
// 'nike zoom',
// '耐克跑步鞋',
// '驭帅11',
// '杜兰特',
// '袜子 男',
// 'lebron',
// '科比ad',
// '挎包',
// '椰子500',
// '长裤',
// '库里',
// '斯凯奇',
// '欧文2',
// '安踏 篮球鞋',
// '新百伦 new balance',
// '士兵11',
// '维金斯',
// 'PUMA',
// '阿迪达斯 篮球鞋',
// '跑鞋',
// '罗斯8',
// '女鞋',
// 'fila',
// 'lbj15',
// '彪马 鞋',
// 'aj14',
// '腰包',
// '阿迪达斯boost',
// '士兵12',
// '耐克短袖',
// 'bape',
// '休闲鞋',
// '威少',
// '乔丹',
// '耐克 air',
// '足球鞋',
// '科比 kobe',
// 'dickies',
// '大air',
// 'lbj',
// 'aj 乔丹',
// '篮球鞋 男',
// '外套',
// '冠军 t恤',
// 'superme',
// '耐克跑鞋',
// '贝壳头',
// '束脚裤',
// '李宁 鞋',
// 'kt3',
// 'aj8',
// '韦德之道6',
// '库里4',
// 'AJ11',
// 'pg',
// '耐克外套',
// 'Kobe',
// '回天之力',
// 'react',
// '斜挎包',
// 'newbalance',
// '中国李宁',
// '匡威 all star',
// '耐克拖鞋',
// 'sb',
// '长袖',
// '阿迪',
// '单肩包',
// 'air force',
// '巴黎世家',
// 'max',
// 'aj2',
// '小椰子',
// '工装裤 男',
// '小闪电',
// '双肩包 男',
// '科比11',
// 'Aj',
// '羽绒服',
// '詹15',
// '李宁悟道',
// '驭帅12',
// '精英袜',
// 'reebok',
// '蓝牙耳机',
// 'Vans',
// '阿迪达斯 三叶草',
// '鸳鸯',
// 'hd2016',
// '使节9',
// '驭帅',
// '护膝',
// '帆布鞋',
// 'Nike篮球鞋',
// 'aj1鸳鸯',
// 'super fly',
// '库里5',
// '哈登1',
// '詹姆斯14',
// 'aj10',
// 'nike拖鞋',
// '空军',
// '小白鞋',
// 'aj30',
// 'ub',
// '罗斯7',
// '音速6',
// '彪马 t恤',
// 'aj1小闪电',
// '耐克 air max',
// 'nike 篮球鞋',
// '詹姆斯11',
// 'aj15',
// 'hd2018',
// '阿迪达斯篮球鞋',
// '詹姆斯12',
// '耐克 篮球鞋',
// '衬衫 男',
// '利拉德3',
// '李宁跑鞋',
// '渔夫帽',
// '菲董',
// 'aj312',
// '运动长裤',
// '黑武士',
// '足球鞋 男',
// '棒球帽',
// '保罗',
// 'EQT',
// 'thrasher',
// '运动鞋',
// 'dunk sb',
// '夹克',
// 'pure boost',
// '匹克',
// '外套男',
// '詹姆斯13',
// '耐克女鞋',
// '联名',
// '冠军 卫衣',
// 'aj9',
// 'boy',
// '篮球袜',
// '衬衫',
// '背心 男',
// '棒球服',
// '高帮',
// '教练夹克',
// 'dw',
// 'nike跑鞋',
// '篮球服',
// 'nike外套',
// '童鞋',
// '宇航员',
// 'Jordan',
// 'champion 卫衣',
// '彪马 休闲鞋',
// '保罗乔治',
// '耐克板鞋',
// 'why not',
// 'dunk',
// '欧文 kyrie',
// '毒液5',
// 'kobe ad',
// '科比12',
// 'crazy',
// '泡',
// '彪马外套',
// '科比10',
// '表',
// '牛仔裤 男',
// '手机',
// '麦迪',
// 'champion t恤',
// '格里芬',
// 'nike篮球鞋',
// '使节',
// '牛仔外套',
// '背包',
// 'puma 鞋',
// '士兵10',
// '悟道2',
// 'yeezy500',
// '手表 男',
// '长袜',
// 'kd9',
// 'max97',
// '钱包',
// '阿迪达斯短袖',
// 'AJ13',
// 't恤',
// 'AF1',
// 'beats',
// 'rose',
// '战士12',
// '低帮篮球鞋',
// '音速',
// '乔丹 aj',
// '阿甘',
// '范斯',
// 'nike包',
// '欧文1',
// '跑步鞋',
// '97',
// 'nb',
// '阿迪达斯卫衣',
// '阿迪达斯板鞋',
// '士兵',
// '科比毒液',
// '詹姆斯10',
// '串标',
// 'aj29',
// 'aj18',
// '科比9',
// 'gucci',
// '手机壳',
// '紧身裤',
// '胸包',
// '战士11',
// 'af force',
// '鸭舌帽',
// '音速5',
// '运动短裤',
// 'palace',
// '阿迪达斯长裤',
// 'Aj1',
// 'superstar',
// '熊猫',
// '银子弹',
// 'clot',
// 'aj28',
// 'cp3',
// '川久保玲',
// 'air max 90',
// 'Air',
// '使节10',
// 'new balance',
// '李维斯',
// '优衣库',
// '匡威 鞋',
// '白鞋',
// 'air max 97',
// '拖鞋 女',
// '耐克长裤',
// 'kd 杜兰特',
// 'pony',
// '耐克包',
// '洗面奶',
// '新百伦574',
// '耐克卫衣',
// '李宁 休闲鞋',
// '休闲裤',
// 'Stussy',
// '短裤男',
// '北卡蓝',
// '耐克短裤',
// 'AJ32',
// '子弹',
// 'asics',
// '汤普森',
// 'aj16',
// 'casio',
// '耐克休闲鞋',
// 'flyknit',
// '耐克 女子 鞋',
// '艾弗森',
// '帽衫',
// '气垫',
// 'nike 跑鞋',
// '阿尔法',
// '鞋',
// 'm2k',
// 'ow',
// 'aj短裤',
// '三叶草 t恤',
// '九分裤',
// '准者',
// '李宁跑步鞋',
// '耐克sb',
// '凉鞋',
// '护踝',
// 'aj1mid',
// '吕布',
// '内裤',
// 'nike短裤',
// 'the north face',
// 'aj1芝加哥',
// 'boy london',
// '彪马 夹克',
// '500',
// 'zoom fly',
// '彪马卫衣',
// '帽子',
// 'pegasus',
// '耐克T恤',
// 'lunar',
// '内裤 男',
// '紧身衣',
// '阿迪达斯拖鞋',
// 'nike卫衣',
// 'bounce',
// 'inxx',
// '飞跃',
// 'nike free',
// 'tubular',
// 'Nike跑鞋',
// 'y3',
// '休闲鞋 男',
// '阿迪达斯短裤',
// '安踏 跑鞋',
// '卫衣 女',
// '270',
// '女 鞋',
// 'kappa',
// '速干',
// 'aj23',
// '牛仔裤',
// 'AJ4',
// 'Nike外套',
// 'aj17',
// '詹姆斯16',
// 'Air max',
// '冲锋衣',
// 'presto',
// 'aj短袖',
// '芝加哥',
// 'aj22',
// '霍华德',
// '斐乐 鞋',
// '毒液',
// '北面',
// 'nike短袖',
// 'AJ3',
// 'adidas boost',
// 'aj篮球鞋',
// 'byw',
// '安东尼',
// '滑板鞋',
// 'Nike短袖',
// 'puma t恤',
// '隐蔽者',
// '开口笑',
// 'hyperdunk2016',
// '1970s',
// 'PG2',
// '篮球鞋 耐克',
// '史密斯',
// '2017',
// '无袖',
// '科比8',
// 'Nike拖鞋',
// 'Puma',
// 'aj1联名',
// 'kd8',
// '李宁韦德之道',
// 'Nike sb',
// 'timberland',
// '回到未来',
// '科比1',
// '詹姆斯 耐克',
// 'aj13熊猫',
// '特步',
// '鬼冢虎 鞋',
// '361',
// 'stance',
// 'crazylight',
// '伦纳德',
// '曼巴精神',
// '耐克zoom',
// 'hyperdunk2017',
// '彪马拖鞋',
// '安德玛 鞋',
// 'off',
// 't恤 男',
// '夹克 男',
// '匡威开口笑',
// 'ub4.0',
// '库里3',
// '鸿星尔克',
// 'nike t恤',
// '阿迪达斯包',
// '破洞牛仔裤',
// 'Boost',
// 'air max97',
// 'aj1禁穿',
// '安踏 休闲鞋',
// '项链',
// '勒布朗',
// '登月',
// '七分裤',
// 'af',
// '2018',
// '韦德之道5',
// 'KD',
// '鼠标',
// 'acg',
// 'aj20',
// 'aj鸳鸯',
// 'one star',
// '球裤',
// '匡威 双肩包',
// '帽衫 男',
// '篮球裤',
// '天足',
// 'puma拖鞋',
// 'Champion',
// 'FILA',
// 'aj21',
// 'air more',
// 'AJ6',
// '福神',
// '杜兰特11',
// 'NMD',
// 'Dickies',
// 'nike板鞋',
// 'kd5',
// '四色鸳鸯',
// '罗斯6',
// '开拓者',
// '腰带',
// 'Air force 1',
// 'just do it',
// '阿迪达斯跑鞋',
// 'soldier',
// '手环',
// '板鞋 耐克',
// 'aj1北卡蓝',
// 'sock',
// '三叶草 鞋',
// 'Nike air',
// '战士',
// 'aj 1',
// 'stan smith',
// '发带',
// '跑鞋 男',
// 'aj1阴阳',
// '皮带',
// '羽绒服 男',
// 'aj19',
// '匹克 篮球鞋',
// '马丁靴',
// 'ripndip',
// '人字拖',
// 'prophere',
// '紧身衣 Nike Pro',
// '安德玛拖鞋',
// '闪击3',
// '韦德之道4',
// 'max90',
// '亚瑟士 asics',
// '杜兰特10',
// 'HD2017',
// 'nike长裤',
// '亚瑟士 跑鞋',
// '保罗 cp',
// '黑红脚趾',
// '充电宝',
// '新百伦999',
// '阿迪达斯运动裤',
// '1970',
// '护臂',
// '情侣',
// 'madness',
// '阿迪达斯贝壳头',
// 'LBJ15',
// 'ssur',
// '威少1',
// '运动长裤 男',
// 'HD',
// 'assc',
// '情侣鞋',
// '篮球鞋 女',
// '运动背心',
// 'hd2015',
// 'puma外套',
// '阿迪达斯裤',
// 'ua',
// 'AJ5',
// 'kyrie',
// '球衣 男',
// '阿迪达斯 男子',
// 'nike 鞋',
// 't恤女',
// '使节8',
// '外套女',
// '索康尼',
// 'aj1low',
// '卡西欧 运动手表',
// '帕克',
// '欧文4简版',
// 'Nike zoom',
// '李宁卫衣',
// 'polo衫',
// 'vapor',
// '李宁拖鞋',
// '阿迪达斯 夹克',
// '回力 鞋',
// '子弹头',
// '312',
// 'aj小闪电',
// 'zk1',
// '匡威包',
// '李宁短袖',
// '球鞋90秒',
// '天梭',
// '耐克男鞋',
// 'Casio',
// '詹姆斯球衣',
// '乔治',
// '苹果',
// 'aj1伦纳德',
// 'vlone',
// '飞马',
// 'Adidas卫衣',
// 'nike air force',
// 'evisu',
// 'puma卫衣',
// '安踏篮球鞋',
// '紧身裤 男',
// '宽松',
// '彪马短袖',
// '杜兰特9',
// '老爹',
// '裤',
// 'aj1低帮',
// '行李箱',
// '要疯',
// 'vans t恤',
// '美津浓',
// 'g shock',
// 'Aj11',
// 'nike袜子',
// '匡威 休闲鞋',
// '库里2.5',
// '紧身衣 男',
// '连帽卫衣',
// 'curry',
// '毒液6',
// '战士10',
// '添柏岚',
// '火焰',
// '双肩包 女',
// '背包 双肩',
// '可口可乐',
// '禁穿',
// '阿迪达斯T恤',
// '华为',
// '阿迪达斯休闲鞋',
// '13',
// 'blazer',
// '罗斯5',
// 'aj1影子',
// '耐克袜子',
// '士兵9',
// '新百伦580',
// '詹14',
// '350',
// 'kd7',
// 'puma 休闲鞋',
// '李宁驭帅',
// 'y-3',
// '衣服',
// '詹13',
// 'AJ12',
// 'neo',
// '风衣',
// '黑紫脚趾',
// '耐克air',
// '阿迪外套',
// '训练鞋',
// '迷彩裤',
// 'kt',
// '复古',
// 'aj33',
// '钱包 男',
// 'aj1 mid',
// '李宁 跑鞋',
// '阿迪达斯夹克',
// 'Adidas外套',
// 'VANS',
// 'lbj14',
// '李宁韦德',
// 'hd2014',
// 'vans包',
// '女 t恤',
// '欧文四',
// 'NB',
// 'air max 95',
// 'nikesb',
// '工装短裤',
// '运动裤男',
// 'ck',
// 'Adidas boost',
// 'melo',
// '剃须刀',
// '哈伦裤',
// '小米',
// '回力 休闲鞋',
// '男鞋',
// '科比AD',
// '羽毛球鞋',
// '黑脚趾',
// 'KD11',
// 'PG2.5',
// '冠军卫衣',
// 'Nike长裤',
// 'aj1.5',
// 'aj1变色龙',
// 'harden',
// '卫衣男',
// '头带',
// '贝壳 头 三叶草',
// 'Gucci',
// '嘻哈',
// 'nasa',
// 'rose9',
// '闪电',
// '匡威高帮',
// '哈达威',
// '耐克背心',
// 'air zoom',
// 'eqt boost',
// '热款',
// '彪马长裤',
// '运动内衣',
// 'nike hyperdunk',
// '国潮',
// '护膝 男',
// '李宁音速6',
// 'SB',
// '乳腺癌',
// '全城5',
// '詹16',
// '阿迪达斯女鞋',
// '哈登3',
// '小狮子',
// '情侣装',
// 'Nike包',
// '北极狐',
// 'AJ31',
// 'nike跑步鞋',
// '威金斯',
// '11',
// 'pod',
// '安踏 鞋',
// '袜子鞋',
// '阿迪卫衣',
// 'KD10',
// 'exp',
// 'max98',
// 'ultra',
// '闪击',
// 'AJ拖鞋',
// '帝客',
// '球鞋',
// '阿迪拖鞋',
// 'jbl',
// '李宁音速',
// 'AJ7',
// 'PG',
// 'yeezy350',
// '威斯布鲁克',
// '彪马板鞋',
// 'Air Jordan',
// 'kd6',
// 'Asics',
// 'huarache',
// 'tiger',
// '匡威 t恤',
// '速干衣',
// 'yezzy',
// '卡帕',
// '卫裤',
// '科比 耐克',
// '重燃',
// 'Lebron',
// 'PG1',
// 'max95',
// 'under armour',
// '彪马 运动鞋',
// '手链',
// '斯图西',
// '游戏本',
// 'jdi',
// 'kd4',
// 'levis',
// '安德玛 篮球鞋',
// '欧文三',
// 'Aape',
// '球袜',
// '2k4',
// '帽子 男',
// '彪马 跑鞋',
// 'aj背心',
// 'lv',
// 'vans 鞋',
// '乔丹 篮球鞋',
// '袜',
// '詹姆斯1',
// '詹姆斯士兵',
// '凤舞',
// '耐克运动裤',
// '钉鞋',
// '阿迪达斯跑步鞋',
// '32',
// 'revenge',
// '中国风',
// '实战',
// '连帽衫',
// 'DW',
// 'crocs',
// 'lbj13',
// '变色龙',
// '库里2',
// '美特斯邦威',
// '阿迪达斯eqt',
// 'NIKE',
// '一脚蹬',
// '锐步 鞋',
// 'carhartt',
// 'kobe11',
// '短袜',
// '黑水泥',
// 'Nike板鞋',
// 'iniki',
// '笔记本',
// '李宁休闲鞋',
// '鲍鱼喷',
// 'ub3.0',
// '六冠王',
// 'free',
// '格子衬衫',
// 'Supreme',
// 'adidas外套',
// 'airmax',
// '战士9',
// '湖人',
// 'iPhone x',
// 'aj1黑紫',
// 'lebron icon',
// '利拉德2',
// '古驰',
// '阿迪包',
// 'wow6',
// '网球鞋',
// '训练鞋 男',
// '匡威联名',
// '小米8',
// '男 polo衫',
// '皮带 男',
// 'Af1',
// 'air max 98',
// '匹克篮球鞋',
// '护腕',
// '机械键盘',
// '98',
// 'aj1黑脚趾',
// 'aj长裤',
// 'kt2',
// 'supreme卫衣',
// '巴特勒',
// '阿迪达斯羽绒服',
// 'Kobe ad',
// 'champion卫衣',
// 'crazy light',
// 'alpha',
// 'huf',
// 'cp',
// 'dame4',
// 'jansport',
// '实战篮球鞋',
// '棉服',
// '运动袜',
// 'kayano',
// 'pro',
// 'vans短袖',
// '口红',
// '男短裤',
// '蕾哈娜',
// 'Nike air max',
// 'aj1扣碎',
// 'foamposite',
// 'nike鞋',
// '耐克华莱士',
// 'Aj13',
// 'Yeezy',
// 'james',
// 'kobe1',
// '运短袖',
// '科比篮球鞋',
// '耐克 男子',
// '耐克空军一号',
// '音速4',
// 'Nike SB',
// 'kobe ad mid',
// '哈登 耐克',
// 'Nike Air',
// 'cdg',
// '詹姆斯9',
// '耐克气垫',
// 'ipad',
// '单肩包 男',
// 'aj1四色鸳鸯',
// 'fly',
// 'lbj16',
// '足球',
// '迪卡侬',
// 'adidas包',
// '三叶草 休闲鞋',
// '冠军 夹克',
// '大皮蓬',
// '手表 女',
// '李宁 夹克',
// '阿迪达斯裤子',
// '阿迪达斯书包',
// 'Y3',
// 'adidas拖鞋',
// 'nike夹克',
// 'BAPE',
// 'Nike袜子',
// 'air max98',
// 'aj1编织',
// '詹姆斯士兵11',
// 't恤 女',
// '李宁驭帅11',
// 'aj外套',
// 'iPhone',
// '包类 男',
// '腰包 男',
// '藤原浩',
// '蛋白粉',
// '阿迪达斯双肩包',
// 'dickies包',
// 'switch',
// '冲锋衣 男',
// 'adidas长裤',
// 'aj26',
// 'more money',
// 'nike女鞋',
// '空军一号联名',
// 'aj1纯白',
// 'hyper',
// '匡威帆布鞋',
// '大气垫',
// '安德玛 t恤',
// '阿甘鞋',
// '阿迪达斯阿尔法',
// 'Hyperdunk',
// 'New balance',
// 'aj1闪电',
// 'icon',
// 'nike运动鞋',
// 'undefeated',
// '音速3',
// '飞马35',
// 'air max 270',
// 'aj童鞋',
// 'hd17',
// '匡威1970',
// '李宁凤舞',
// '条纹衬衫',
// '男',
// '男裤',
// '耐克运动鞋',
// '西铁城',
// '詹姆斯使节',
// '铁三角',
// 'killwinner',
// 'superfly',
// '亚瑟士 鞋',
// 'nike flyknit',
// '亚瑟士 asics gel',
// '大魔王',
// '电脑',
// '运动长裤 女',
// '郭艾伦',
// '锐步 跑鞋',
// '阿迪达斯neo',
// 'Nike卫衣',
// 'ad',
// 'yeezy 500',
// '安踏老爹鞋',
// '耐克双肩包',
// 'Air Max',
// 'ascis',
// 'fila 鞋',
// 'hipanda',
// 'nike 休闲鞋',
// 'puma 跑鞋',
// '三叶草外套',
// '彪马女鞋',
// '彪马蕾哈娜',
// '李宁悟道2',
// '李小龙',
// '鬼冢虎 休闲鞋',
// 'aj1 low',
// 'kith',
// '冠军短裤',
// '飞线',
// '高帮鞋',
// 'air max95',
// 'aj1情人节',
// 'nike dunk',
// '林书豪',
// '童',
// '粉',
// '耐克登月',
// '袜套鞋',
// '阿迪达斯运动鞋',
// '索尼',
// 'aj24',
// 'lebron x',
// 'nike休闲鞋',
// '休闲长裤',
// '保温杯',
// '帆布包',
// '足球服',
// 'aj女',
// '杰克琼斯',
// '空袭',
// '赤足',
// '键盘',
// '防晒衣',
// '鞋垫',
// 'Adidas鞋',
// 'Aj4',
// 'adidas nmd',
// 'boy london t恤',
// 'supreme短袖',
// 'vivo',
// '低帮',
// 'aj1黑紫脚趾',
// 'aj1黑红',
// 'nike 跑步鞋',
// '保罗乔治2',
// '彪马包',
// '邮差包',
// '风衣 男',
// '香水',
// 'champion 夹克',
// 'nike裤',
// '清风',
// '登月8',
// '粉色',
// 'AIR JORDAN',
// 'airmax97',
// 'mid',
// 'mlb',
// 'nike sock dart',
// '保罗10',
// '旅行包',
// '洗发水',
// '科10',
// '科比360',
// '隆多',
// 'aj 11',
// 'aj fly',
// 'force',
// '凯尔特人',
// '女外套',
// '杜兰特8',
// '洗面奶 男',
// '运动裤女',
// '陈冠希',
// '魔术贴',
// 'AIR',
// 'Adidas eqt',
// 'jordan brand',
// '冬季',
// '科11',
// '运动耳机',
// '迷彩',
// '阿迪达斯小椰子',
// 'Nike跑步鞋',
// 'beats 头戴式耳机',
// 'flight',
// 'nike vapor',
// 'sb dunk',
// '收脚裤',
// '潮牌',
// '风',
// 'Aj3',
// 'aj1丝绸',
// 'dickies t恤',
// 'hipanda t恤',
// 'rose8',
// '休闲鞋 女',
// '维斯布鲁克',
// '绿尾',
// '95',
// 'puma包',
// 'rothco',
// '七分袖',
// '匡威卫衣',
// '帕拉丁',
// '椰子700',
// '耐克书包',
// 'LeBron',
// 'adidas crazy',
// 'dickies 双肩包',
// 'vans双肩包',
// '匡威 夹克',
// '耐克t恤',
// '运动拖鞋',
// '阿迪板鞋',
// 'Bape',
// '李宁重燃',
// '沃尔',
// '耐克宇航员',
// 'aj女鞋',
// 'hdx',
// '套头衫',
// '耐克裤',
// '阿迪短裤',
// '2016',
// 'crazy explosive',
// 'nike m2k',
// 'nike react',
// '三叶草卫衣',
// '戴维斯',
// 'air max270',
// 'nike max',
// '七号宇宙',
// '匡威one star',
// '洞洞鞋',
// '编织',
// '12',
// 'Eqt',
// 'aj卫衣',
// '万斯高帮',
// '新欢',
// '无线耳机',
// '李宁云',
// 'air more money',
// 'aj1黑白',
// 'explosive',
// '大衣',
// '扣碎',
// '斯凯奇 鞋',
// '毛巾',
// '特步 鞋',
// '耐克SB',
// '詹姆斯士兵12',
// '贪玩蓝月',
// 'KT3',
// 'Nikesb',
// 'aj1黑红脚趾',
// 'aj联名',
// 'turbo',
// '乔11',
// '匡威经典款',
// '科比毒液5',
// '足球鞋TF',
// '阿迪达斯高帮',
// '飞行员夹克',
// '鲨鱼',
// 'HD2018',
// 'NASA',
// 'adidasi短袖',
// 'uptempo',
// '奥尼尔',
// '漫威',
// '科比6',
// 'future',
// 'iphone',
// '半袖',
// '布鞋',
// '杰斯伯',
// '贝壳',
// '运动鞋男',
// '阿迪达斯t恤',
// '1',
// 'aj1女',
// 'hyperdunk2018',
// '体恤',
// '保罗9',
// '洗鞋',
// '牛仔衬衫',
// '詹12',
// '马甲',
// 'Nike女鞋',
// 'Vapormax',
// 'nba',
// '女装',
// '李宁外套',
// '李宁运动鞋',
// '袜子 女',
// '酷玩潮品',
// '黑白',
// 'adidas eqt',
// 'aj25',
// 'aj27',
// 'staple',
// '三叶草 夹克',
// '森海塞尔',
// '水杯',
// '耐克老爹鞋',
// '詹11',
// '高帮篮球鞋',
// 'BOY',
// 'air max 1',
// 'lbj11',
// 'nike 拖鞋',
// '休闲短裤',
// '儿童',
// '彪马短裤',
// '欧文球衣',
// '电脑包',
// '阿迪达斯 板鞋',
// '阿迪达斯椰子',
// 'Adidas拖鞋',
// 'kobe10',
// 'lunarepic',
// '大眼睛',
// '李宁蝴蝶',
// '科比7',
// '锐步 休闲鞋',
// '阿迪达斯 外套',
// 'adidas originals',
// 'climacool',
// 'dame',
// 'kaws',
// 'kb',
// 'max270',
// 'sock dart',
// 'vans高帮',
// '彪马双肩包',
// '皮鞋',
// '574',
// 'LBJ',
// 'puma 夹克',
// 'rose7',
// 'stance 袜子',
// 'supreme 夹克',
// 'Adidas neo',
// 'aj四色鸳鸯',
// 'gel',
// 'kwazi',
// 'vans 夹克',
// '尼克杨',
// '斯派克李',
// '李宁闪击',
// '欧文 耐克',
// '牛仔夹克',
// '耐克开拓者',
// '雨伞',
// 'champion 帽衫',
// 'kobead',
// 'nike球鞋',
// '夹克 女',
// '护腿',
// '李宁 悟道',
// '李宁驭帅12',
// '气垫鞋',
// '驭帅10',
// 'Boy',
// 'PUMA卫衣',
// 'aj1新欢',
// 'hyperdunk x',
// 'zara',
// '亚瑟士 休闲鞋',
// '李宁无界',
// '李宁音速5',
// '欧文简版',
// '阿迪达斯EQT',
// 'adidas neo',
// 'champion包',
// 'g-shock',
// 'lbj12',
// 'roshe',
// '健身包',
// '多威',
// '手提包',
// '紫脚趾',
// '耐克裤子',
// 'gap',
// 'iPad',
// 'kt4',
// 'lbj10',
// 'rick owens',
// 'trainer',
// '安踏跑鞋',
// '平板电脑',
// '曼联',
// '阿迪达斯外套男',
// 'Air jordan',
// 'Rose',
// 'Timberland',
// 'air money',
// 'aj1黑金',
// 'nike air huarache',
// 'saucony',
// 'vans棋盘格',
// 'yung',
// '三叶草 卫衣',
// '女 跑鞋',
// '施华洛世奇',
// '运动手表',
// '990',
// 'adidas t恤',
// 'supreme包',
// '凉鞋 男',
// '日系',
// '欧文4low',
// '科比球衣',
// '耐克联名',
// '锐步 篮球鞋',
// 'aj熊猫',
// 'polo',
// 'sk8',
// '奥利奥',
// '彪马男裤',
// '戒指',
// '荣耀10',
// '运动卫衣',
// '阿迪女鞋',
// '韦德悟道',
// 'Aj32',
// 'herschel',
// '乔1',
// '五分裤',
// '小麦',
// '李宁 蓝',
// '李宁溯',
// '海贼王',
// '登月9',
// '耐克外套男',
// '耐克羽绒服',
// 'Max',
// 'Pegasus',
// 'jansport 双肩包',
// '全城',
// '新百伦990',
// '李宁运动裤',
// '杜11',
// '白色板鞋',
// '裂变',
// '裤子男',
// '跑鞋 女',
// 'nike 袜子',
// 'whynot',
// '中帮',
// '匡威双肩包',
// '匡威经典',
// '小吕布',
// '护腰',
// '无界',
// '李宁T恤',
// '科比5',
// '耐克大气垫',
// '阴阳',
// 'James',
// 'Nike华莱士',
// 'Nike短裤',
// 'aj1黄蜂',
// 'aj3黑水泥',
// 'vans 滑板鞋',
// '加内特',
// '始祖鸟',
// '束腿裤',
// '欧文5',
// '牛仔裤男',
// '球服',
// '紧身裤 女',
// '运动鞋女',
// '阿迪跑鞋',
// 'aj低帮',
// 'gshock',
// '复活节',
// '抽绳包',
// '新百伦 跑鞋',
// '杜兰特5',
// '爆米花',
// '特步 跑鞋',
// '詹姆斯使节10',
// '韦德之道3',
// '魅族',
// 'Adidas篮球鞋',
// 'Air force',
// 'Kappa',
// 'NBA',
// 'aj11变色龙',
// 'aj1小芝加哥',
// 'energy boost',
// 'nike air more',
// 'zx500',
// '影子',
// '眼镜',
// '高帮板鞋',
// 'flytrap',
// 'nike blazer',
// '小芝加哥',
// '火箭',
// '直筒裤',
// '空军一号高帮',
// '要疯2',
// 'aj1拉链',
// 'nike宇航员',
// '匡威 篮球鞋',
// '卡特',
// '墨镜',
// '牛仔',
// '耐克足球鞋',
// '阿迪达斯 boost',
// '鲍尔芬',
// 'T恤女',
// 'aj1ow',
// 'anta',
// '乔治2',
// '北极狐 双肩包',
// '机能',
// '网球鞋 男',
// '踢不烂',
// '霍华德3',
// '鞋带',
// '风行者',
// '马 鞋',
// 'air max1',
// 'dr. martens',
// 'hd16',
// 'lining',
// 'puma suede',
// '三星',
// '卫衣女',
// '沐浴露',
// '男装',
// '篮球鞋 aj',
// '粉喷',
// '韦德之道7',
// '高帮休闲鞋',
// 'air force1',
// 'aj1六冠王',
// 'aj1绿脚趾',
// 'nike华莱士',
// 'nike开拓者',
// 'offwhite',
// 'premier',
// 'vans 万斯',
// '太平鸟',
// '手套',
// '新百伦女鞋',
// '羽毛球鞋 男',
// '运动夹克',
// '队尚',
// '防风衣',
// '阿玛尼',
// '飞机杯',
// 'HD2016',
// 'aJ',
// 'aj1皇家蓝',
// 'cat',
// 'ssur plus',
// '安德玛 紧身衣',
// '工装',
// '耐克飞线',
// '袜套',
// '训练包',
// '轻骑兵',
// 'Aj6',
// 'adv',
// 'aj11low',
// 'aj1黑灰',
// 'hm',
// 'nike dunk sb',
// 'pump',
// 'tmac',
// '伞',
// '套头卫衣',
// '安踏nasa',
// '灌篮高手',
// '球鞋洗剂',
// '避孕套',
// '靴子',
// 'AAPE',
// 'AJ14',
// 'alpha bounce',
// 'anti social social club',
// 'ultra fly',
// 'yeezy700',
// '佳得乐',
// '军绿',
// '库里1',
// '御空',
// '涂鸦',
// '金标',
// '4',
// 'CK',
// 'puma蝴蝶结',
// 'rastaclat',
// '保罗11',
// '套装 男',
// '帽',
// '彪马运动裤',
// '男卫衣',
// 'Nike Air Max',
// 'epic',
// 'kindle',
// 'sup',
// 'zx750',
// '兔八哥',
// '情人节',
// '李维斯 t恤',
// '椰子750',
// '耐克air max',
// '跑步',
// '防水',
// '阿迪贝壳头',
// 'Adidas短裤',
// 'aj1紫脚趾',
// 'oppo',
// 'the ten',
// '休闲',
// '全城6',
// '女款',
// '小米6',
// '布鲁克斯',
// '斯伯丁',
// '男士外套',
// '篮球包',
// '篮球鞋 nike',
// '衬衣',
// '运动袜子',
// '鸳鸯鞋',
// '黑绿脚趾',
// '31',
// 'aj 4',
// 'curry5',
// 'hu',
// 'new era',
// '椰子鞋',
// '纪梵希',
// '耐克球鞋',
// '詹姆斯使节9',
// '镭射',
// '3',
// 'NIke',
// 'aj1镭射',
// 'puma短裤',
// 'zoom live',
// '李宁板鞋',
// '男士内裤',
// '空军一号小麦色',
// '2k5',
// '87',
// 'Aj5',
// 'aj11大魔王',
// 'aj1黑蓝',
// 'c罗',
// 'gxg',
// 'nimbus',
// 'somethnew',
// '德鲁大叔',
// '悟道ace',
// '李宁短裤',
// '李宁袜子',
// '船袜',
// '詹姆斯篮球鞋',
// '迷彩短裤',
// '阿迪篮球鞋',
// '阿迪达斯背包',
// '360',
// '714',
// '996',
// 'Converse',
// 'nike kobe',
// 'puma蕾哈娜',
// 'zk11',
// '全明星',
// '北卡',
// '匡威 one star',
// '板鞋女',
// '羽毛球拍',
// '耐克T恤男',
// '詹姆斯15low',
// 'Adidas短袖',
// 'Fila',
// 'aj6rings',
// 'nike lunar',
// 'puma短袖',
// 'stussy t恤',
// 'supreme 鞋',
// '丝绸扣碎',
// '余文乐',
// '团购',
// '安踏御空',
// '彪马裤子',
// '戴尔',
// '毛衣',
// '阿迪boost',
// '靴子 男',
// '风一',
// 'AJ2',
// 'Nike Air max',
// 'aj future',
// 'aj1off',
// 'lee',
// 'nike vapormax',
// 'shox',
// '三叶草贝壳头',
// '刀锋战士',
// '包类',
// '森马 t恤',
// '欧文low',
// '白丝绸',
// '罗德曼',
// '耐克夹克',
// '耐克背包',
// '露娜',
// '黑曼巴',
// '361°',
// '361度',
// '998',
// 'AF',
// 'Nike max',
// 'aj北卡蓝',
// 'boy london 卫衣',
// 'cr7',
// 'hd18',
// 'low',
// 'nike acg',
// 'ow联名',
// 'vans联名',
// 'why',
// '剃须刀 男',
// '反光',
// '外套 女',
// '巴克利',
// '棉鞋',
// 'Nmd',
// 'Polo衫',
// 'Zoom',
// 'lunarglide',
// 'mamba',
// 'nike air vapormax',
// 'nike air zoom',
// 'nike sb dunk',
// '串标裤',
// '乔丹 t恤',
// '刺客',
// '勇士',
// '外套 连帽',
// '森马',
// '气垫跑鞋',
// '猎鹰',
// '范斯 鞋',
// '贵人鸟',
// '超轻15',
// 'boost4.0',
// 'champion短裤',
// 'lbj1',
// 'max 97',
// 'money',
// 'nike air foamposite',
// 'nike球衣',
// 'ub4',
// '健身手套',
// '健身短裤',
// '准者 球衣',
// '字母T恤',
// '山雾花野',
// '新百伦996',
// '欧文4低帮',
// '电动牙刷',
// '立领',
// '耐克童鞋',
// '运动长裤男',
// '鞋子',
// '黑红',
// 'Adidas跑鞋',
// 'a',
// 'aj13拖鞋',
// 'bape外套',
// '中国',
// '宽松裤男',
// '樱木花道',
// '破洞裤',
// '耐克腰包',
// '詹10',
// '针织运动裤',
// '鞋 男',
// '飞马34',
// '黑金',
// 'DW手表',
// 'Kobe1',
// 'NikeSB',
// 'Y-3',
// 'foam',
// 'hyperrev',
// 'nike air presto',
// 'nike zoom fly',
// 'nike 足球',
// '彪马跑鞋',
// '滑板',
// '短袖男',
// '绿脚趾',
// '艾佛森',
// '阿迪达斯superstar',
// '阿迪达斯女',
// 'AJ1小闪电',
// 'NIKE SB',
// 'adidas prophere',
// 'aj 32',
// 'aj1电镀银',
// 'kappa卫衣',
// 'puma女鞋',
// 'suamoment',
// 'super',
// '万斯包',
// '优衣库 t恤',
// '全掌气垫',
// '女运动鞋',
// '安踏运动鞋',
// '巴特勒2',
// '情侣卫衣',
// '篮球鞋阿迪达斯',
// '纯白',
// '耐克子弹',
// '蝴蝶',
// '速干t恤',
// '阿尔法跑鞋',
// '黑紫',
// '16',
// 'Nike 篮球鞋',
// 'aj3 jth',
// 'nba 球衣',
// 'nike lebron',
// 'nike presto',
// 'smith',
// '哑铃',
// '夜光',
// '头巾',
// '工装裤 女',
// '打底衫',
// '李宁t恤',
// '短裤 女',
// '科比曼巴精神',
// '荣耀',
// '解构',
// 'CLOT',
// 'Nike气垫',
// 'aj包',
// 'campus',
// 'ck内裤',
// 'nba t恤',
// 'nike 板鞋',
// 'nike裤子',
// 'vans卫衣',
// 'yeezy 350',
// '乔13',
// '勒布朗15',
// '威尔胜',
// '悟空',
// '懒人鞋',
// '斐乐 夹克',
// '棉衣',
// '篮球鞋李宁',
// '罗斯4',
// '阿迪达斯 跑鞋',
// '阿迪达斯袜子',
// '鞋子男',
// 'AJ30',
// 'Adidas三叶草',
// 'Aj拖鞋',
// 'adidas卫衣',
// 'adidas双肩包',
// 'adidas短袖',
// 'aj11复活节',
// 'champion 运动短裤',
// 'kenzo',
// 'kobe9',
// 'legacy',
// 'nike roshe',
// 'nike 短裤',
// 'nike紧身裤',
// 'puma fenty',
// 'vans 休闲鞋',
// '日系短袖 男',
// '登山鞋',
// '短裤休闲',
// '篮球短裤',
// '詹姆斯8',
// '赛睿',
// '阿迪短袖',
// '音响',
// '马克华菲',
// 'Crazy',
// 'aj编织',
// 'coach',
// 'penny',
// 'sf',
// 'ugg',
// 'zoom x',
// '匡威书包',
// '双肩背',
// '惠普',
// '短裤工装',
// '空袭4',
// '耐克max',
// '虎扑优选',
// '识货',
// '道袍',
// '阿迪达斯 休闲鞋',
// '阿迪达斯 卫衣',
// '魅族16',
// '9分裤',
// 'KD9',
// 'Nike休闲鞋',
// 'Off white',
// 'ace',
// 'elite',
// 'jack & jones',
// 'puma basket',
// 'zx',
// '保罗乔治1',
// '小禁穿',
// '李宁女鞋',
// '水泥地',
// '男背心',
// '篮球鞋耐克',
// '罗斯篮球鞋',
// '耐克紧身裤',
// '耐克长袖',
// '贝壳鞋',
// '超轻',
// '透气',
// '阿迪达斯 长裤',
// '阿迪达斯背心',
// '黑红禁穿',
// '15',
// '6',
// '750',
// 'adidas女鞋',
// 'aj1熊猫',
// 'aj1黑绿',
// 'aj运动裤',
// 'champion 运动长裤',
// 'kobe8',
// 'nike书包',
// 'nike老爹鞋',
// 'pro bounce',
// 'vapor max',
// 'zoomfly',
// '儿童鞋',
// '全员恶人',
// '天伯伦',
// '尤文图斯',
// '巴塞罗那',
// '斯伯丁 篮球',
// '格子裤',
// '油头',
// '皮鞋 男',
// '第六人',
// '足球袜',
// '阿迪达斯男鞋',
// '34',
// 'Adidas夹克',
// 'Adidas跑步鞋',
// 'G shock',
// 'PUMA拖鞋',
// 'air monarch',
// 'aj1小禁穿',
// 'ecco',
// 'element',
// 'epic react',
// 'nike空军一号',
// 'wass up',
// 'zoomx',
// '丝绸',
// '复古跑鞋',
// '情侣短袖',
// '板鞋男',
// '科比球鞋',
// '耐克球衣',
// '阿迪达斯防风衣',
// '阿里纳斯',
// '龙珠',
// '35',
// '70s',
// 'AJ8',
// 'Nike 跑步鞋',
// 'Nike夹克',
// 'adidas 外套',
// 'adidas男外套',
// 'aj 6',
// 'aj11拖鞋',
// 'aj1佳得乐',
// 'aj1贪玩蓝月',
// 'aj30.5',
// 'c2h4',
// 'nb990',
// 'sf af1',
// 'soldier12',
// 'wtaps',
// '中筒袜',
// '冠军裤',
// '南海岸',
// '小麦色',
// '李宁 篮球',
// '泡喷',
// '詹15low',
// '防风',
// '阿迪达斯crazy',
// 'Aj7',
// 'Lee',
// 'Max97',
// 'Nike T恤',
// 'Reebok',
// 'bose',
// 'hyperdunk 2017',
// 'nike air max 97',
// 'nike hd',
// 'onitsuka tiger',
// 'pure',
// 'run',
// 'vans夹克',
// 'whoosis',
// 'zero',
// '串标外套',
// '印花t恤男',
// '圣康尼',
// '彪马串标',
// '彪马男鞋',
// '拖鞋aj',
// '李宁男鞋',
// '牙膏',
// '瑜伽垫',
// '短裤阿迪达斯',
// '科比 ad',
// '移动电源',
// '美特斯邦威 t恤',
// '詹',
// '詹姆斯士兵10',
// '运动长袖',
// 'aj 13',
// 'aj伦纳德',
// 'aj阴阳',
// 'champion袜子',
// 'curry4',
// 'jth',
// 'mp3',
// 'noah',
// 'racer',
// 'woven',
// 'zk',
// '任天堂',
// '休闲长裤 男',
// '吹风机',
// '科12',
// '网球',
// '耐克风行者',
// '运动服',
// '金标贝壳头',
// '阿迪达斯T恤男',
// '阿迪达斯史密斯',
// '阿迪达斯球衣',
// '骷髅头',
// '黑人月',
// '4%',
// 'AJ15',
// 'Adidas板鞋',
// 'NIKE AIR MAX',
// 'Nike宇航员',
// 'aj 女',
// 'aj7加强',
// 'boost篮球鞋',
// 'champion短袖',
// 'nike训练鞋',
// 'nizza',
// '全天',
// '公牛',
// '北面 冲锋衣',
// '布鲁克斯 跑鞋',
// '帽衫/卫衣',
// '护肘',
// '漱口水',
// '猿人头',
// '篮球 男',
// '紧身裤女',
// '长裤女',
// '阿迪长裤',
// '面膜',
// 'Kd',
// 'NBA球衣',
// 'ad mid',
// 'adidas裤子',
// 'air Max',
// 'air max90',
// 'aj 3',
// 'aj1粉',
// 'aj1紫',
// 'aj芝加哥',
// 'boost3.0',
// 'hy',
// 'nike子弹',
// 'top3',
// 'ultraboost',
// 'vandal',
// 'vans sk8',
// 'wade',
// '乔丹32',
// '乔丹体育',
// '冠军外套',
// '刺绣夹克',
// '安踏 汤普森',
// '安踏板鞋',
// '小米6x',
// '文艺',
// '李宁长裤',
// '格子',
// '潮牌短袖',
// '白斑马',
// '科比2',
// '长袖t恤',
// '阿迪小椰子',
// '马拉松',
// '999',
// 'AJ312',
// 'AJ9',
// 'Adidas男鞋',
// 'Jansport',
// 'Pg2',
// 'Superme',
// 'adidas EQT',
// 'air force 270',
// 'aj1伯爵',
// 'aj1绿',
// 'dickies 包',
// 'float',
// 'lebron15',
// 'nike 女鞋',
// 'nmd r2',
// 'super fly 2017',
// 'vapor street',
// 'xdr',
// '中国乔丹',
// '匡威川久保玲',
// '卡宾',
// '李宁超轻',
// '耐克子弹头',
// '耐克阿甘',
// '阿迪达斯外套女',
// '阿迪达斯老爹鞋',
// '阿迪达斯贝壳',
// '雷蛇',
// 'AG足球鞋',
// 'AJ短袖',
// 'Adidas长裤',
// 'EQt',
// 'UA',
// 'aj super fly',
// 'aj1 鸳鸯',
// 'aj1童鞋',
// 'aj4猛龙',
// 'aj禁穿',
// 'aj鞋',
// 'kobe ad ep',
// 'new balance 574',
// '一加6',
// '七分',
// '七龙珠',
// '女包',
// '女运动裤',
// '情侣衣',
// '李宁全天',
// '泡椒',
// '皇马',
// '科比毒液6',
// '移动硬盘',
// '鉴定',
// '阿迪达斯 男鞋',
// '阿迪达斯男裤',
// '飞行夹克',
// 'AD',
// 'Adidas 裤',
// 'Nike 跑鞋',
// 'T恤长',
// 'air max 93',
// 'aj 31',
// 'aj1全明星',
// 'aj袜子',
// 'pb',
// 'rick',
// 'superme卫衣',
// 'supreme T恤',
// 'tanjun',
// '卫衣 连帽',
// '库里球衣',
// '排球鞋',
// '文字',
// '李宁 韦德之道',
// '李宁全场',
// '杜10',
// '杜蕾斯',
// '白卫衣',
// '科比4',
// '耐克 zoom',
// '耐克上衣',
// '运动套装',
// '迪奥',
// '高达',
// '10',
// 'AJ13熊猫',
// 'HD17',
// 'M2K',
// 'Ripndip',
// 'adidas跑步鞋',
// 'af1 mid',
// 'aj 篮球鞋',
// 'aj1小新欢',
// 'nb580',
// 'pureboost',
// 'reebok 鞋',
// 'revenge x storm',
// 'skechers',
// 'yeezy750',
// '入耳式耳机',
// '冬',
// '包类 女',
// '卫衣 圆领',
// '大灌篮',
// '情侣外套',
// '手表 男士',
// '拉杆箱',
// '李宁 韦德',
// '溯',
// '秋冬',
// '索尼耳机',
// '美津浓 跑鞋',
// '耐克复古',
// '运动鞋 男',
// '速干 短裤',
// '金子弹',
// '阿迪达斯nmd',
// '飞马33'];
const keywordsArr = ['迪奥999','迪奥 888','迪奥口红','迪奥唇膏','迪奥唇釉','迪奥红管','dior唇膏','dior口红','ysl方管','ysl圆管','ysl唇釉','ysl星辰','ysl哑光','ysl镜面','ysl唇膏','ysl口红','圣罗兰唇膏','圣罗兰唇釉','ysl 416','mac唇膏','魅可口红','chili','子弹头','纪梵希唇膏','纪梵希小羊皮','纪梵希315','纪梵希禁忌之吻','香奈儿口红','香奈儿唇膏笔','阿玛尼唇釉','阿玛尼唇膏','阿玛尼405','阿玛尼501','阿玛尼烂番茄','TF唇膏','TF黑管','TF白管','TF迷你','nars唇膏笔','nars龙女','nars豆沙','nars唇釉','萝卜丁唇膏','雅诗兰黛口红','雅诗兰黛枫叶','雅诗兰黛豆沙','雅诗兰黛333','burberry唇蜜','burberry唇膏','娇兰亲亲','娇兰宝石','娇兰小黑裙','娇兰唇釉','cpb唇膏','cpb唇釉','兰蔻菁纯','兰蔻唇膏','兰蔻摇摇乐','迪奥凝脂','迪奥粉底','迪奥star','迪奥气垫','ysl超模','ysl逆龄','ysl气垫','ysl粉底','ysl羽毛','ysl蕾丝','纪梵希四宫格','纪梵希散粉','纪梵希粉底','香奈儿气垫','香奈儿粉饼','阿玛尼权利','阿玛尼滴管','阿玛尼气垫','阿玛尼大师','阿玛尼粉底','阿玛尼大红盘','nars粉底','雅诗兰黛DW','雅诗兰黛粉底','娇兰粉底','cpb隔离','age20','age气垫','nyx遮瑕','nyx修容','黛珂散粉','canmake粉饼','砍妹粉饼','canmake棉花糖','zelens粉底','suqqu粉霜','玫珂菲粉霜','covermark粉底','迪奥香水','迪奥真我','迪奥小姐','ysl香水','ysl反转巴黎','ysl鸦片','香奈儿香水','香奈儿5','香奈儿邂逅','香奈儿蔚蓝','阿玛尼香水','阿玛尼寄情','阿玛尼挚爱','祖马龙香水','祖玛珑香水','安娜苏香水','sk2神仙水','奥尔滨健康水','雅诗兰黛眼霜','兰蔻肌底液','黛珂紫苏水','悦木之源菌菇水','sisly全能乳液','lamer面霜','ipsa流金水','UD眼影','tarte眼影','TF眼影'];
const puppeteer = require('puppeteer');
const request = require('request');
const _ = require('lodash');
const url = require('url');
const redis = require('redis');
const config = require(process.cwd() + '/config/develop/app.json');
const redisConfig = config.db.redis;
const redisClient = redis.createClient({
    host: redisConfig.host,
    port: redisConfig.port,
    db: redisConfig.database,
    password: redisConfig.password,
    connect_timeout: 5000,
    socket_keepalive: true
});
const taobaoToken = require(process.cwd()+'/tools/taobaoToken/runList.js');
const redisKey = 'stone2018:keywords2';

const ApiClient = require('ali-topSdk').ApiClient;
const client = new ApiClient({
    'appkey':'23383263',
    'appsecret':'5f9135094c0193fa140dfef0db13c981',
    'REST_URL':'http://gw.api.taobao.com/router/rest'
});
async function browserStart(keywords) {
    var launch = {
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        headless: false
    };
    // const proxyIp = await getProxyip();
    // if (proxyIp) {
    //     console.log(proxyIp)
    //     launch.args.push('--proxy-server='+proxyIp)
    // }
    //Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Mobile Safari/537.36
    const browser = await puppeteer.launch(launch);
    const page = await browser.newPage();
    var searchUrl = 'https://s.taobao.com/search?q='+keywords;
    await page.goto(searchUrl);
    await page.addScriptTag({ url: 'https://cdn.bootcss.com/jquery/2.2.3/jquery.js' });
    await page.waitFor(3000);
    const taobaoUrls = await page.evaluate(() => {
        var  $ = window.$;
        var taobaoUrlsTmp = [];
        $('.m-itemlist .items .item').each(function () {
            if (!$(this).hasClass('item-ad')) {
                taobaoUrlsTmp.push('http:'+$(this).find('a').attr('href'));
            }
        });
        return taobaoUrlsTmp;
    });
    var isNotFound = await page.evaluate(() => {
        var  $ = window.$;
        if ($('.norestip-title').text().indexOf('抱歉！没有找到与') != -1) {
            return true;
        }
        if ($('.item-not-found').text().indexOf('没有找到与') != -1) {
            return true;
        }
        return false;
    });
    var isShoe = await page.evaluate(() => {
        var  $ = window.$;
        if ($('.J_NavGroup').text().indexOf('鞋') != -1) {
            return true;
        }
        return true;
       // return false;
    });
    var isHtml = await page.evaluate(() => {
        var  $ = window.$;
        if ($('body').text()) {
            return true;
        }
        return false;
    });

    // await page.emulate({
    //     userAgent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Mobile Safari/537.36"
    // })
    var urlredisKey = redisKey+keywords;
    var taobaoUrl = '';
    var hasList = hasShihuoWord = 0;
    var getTaobaoUrl = function  () {
        if (taobaoUrl = taobaoUrls.shift()) {
            redisClient.hget(urlredisKey, taobaoUrl, async function (err, result) {
                if (err) {
                    return console.log(err.message);
                }
                if (result) {
                    console.log(keywords, taobaoUrl, 'has');
                    return getTaobaoUrl();
                }

                console.log(keywords, taobaoUrl, 'get...');
                hasList = hasShihuoWord = 0;
                var urlInfo = url.parse(taobaoUrl, true);
                await page.goto('http://h5.m.taobao.com/wendajia/question2017.html?refId='+urlInfo.query.id);
                await page.waitFor(1000);
                await page.focus('#JInput', {delay: 100});
                await page.type('#JInput', '识货', {delay: 73});
            })
        } else {
            console.log(keywords, 'end')
            redisClient.sadd(redisKey, keywords, function () {
                 browser.close();
                console.log(2222)
                 keywordsSearch();
            });
        }
    }

    //var sendImgTime  = Date.now();
    // var si = setInterval(function () {
    //     //超过50s钟
    //     if ((Date.now() - sendImgTime) > 1000*50) {
    //         console.log(3333)
    //         //关闭浏览器
    //         clearInterval(si);
    //         browser.close();
    //         keywordsSearch();
    //     }
    // }, 5000)
    page.on('response', async function (data) {
        //h5api js cookie
        if (data.url.indexOf('http://acs.m.taobao.com/h5/mtop.taobao.social.feed.aggregate') != -1) {
            var text = await data.text();
            text = text.replace(/mtopjsonp(\d+)\(/, '');
            text = _.trim(text, ')')
            text = JSON.parse(text);

            var jsonUrlInfo =  url.parse(data.url, true);
            var postData = decodeURIComponent(jsonUrlInfo.query.data);
            postData = JSON.parse(postData);
            var postparams = JSON.parse(postData.params);

            if (text.ret[0].indexOf('SUCCESS') != -1) {
                //var currentUrl = await page.url();
                if ('total' in text.data) {
                    hasList = text.data.total;
                }
                //结束
                if ('word' in postparams && postparams.word == '识货') {
                    hasShihuoWord = text.data.list.length;//it-name
                    title = await page.evaluate(() => {
                       return  document.querySelector('.it-name').textContent
                    });

                    client.execute('taobao.wireless.share.tpwd.create', {
                        'tpwd_param':JSON.stringify({
                            url : 'http://detail.tmall.com/item.htm?id=572682723691',
                            text: '识货'
                        })
                    }, function(error, response) {
                        if (error){
                            console.log(error, 'create ticket');
                            code = '';
                        } else {
                            code = response.model;
                        }

                        //sendImgTime = Date.now();

                        console.log(keywords, taobaoUrl, 'save...', JSON.stringify({
                            hasList : hasList,
                            hasShihuoWord : hasShihuoWord,
                            code : code,
                            title : title
                        }));
                        redisClient.hset(urlredisKey, taobaoUrl, JSON.stringify({
                            hasList : hasList,
                            hasShihuoWord : hasShihuoWord,
                            code : code,
                            title : title
                        }), function (err, result) {
                            return getTaobaoUrl();
                        });
                    })
                }
            }
        }

        if (data.url.indexOf('https://login.m.taobao.com') != -1) {
            // browser.close();
            // keywordsArr.unshift(keywords);
            // keywordsSearch();
        }

        // if (msg.url.indexOf('https://www.taobao.com/go/act/loginsuccess/taobao.php') != -1) {
        //     console.log(username, 'my fav');
        //     page.goto("https://h5.m.taobao.com/fav/index.htm");
        // }
    });

    console.log(isNotFound, isShoe);
    if (!isNotFound && isShoe) {
        getTaobaoUrl();
    } else {
        browser.close();
        if (isHtml) {
            redisClient.sadd(redisKey, keywords, function () {

            });
            keywordsSearch();
        } else {
            keywordsArr.unshift(keywords);
            keywordsSearch();
        }

    }
    // return  {
    //     taobaoUrls : taobaoUrls, isNotFound : isNotFound,  isShoe :isShoe
    // }
}


//是否有识货的问答
function getSHihuoAsk (itemId) {

    //&api=mtop.taobao.rate.detail&v=4.0&AntiCreep=true&ecode=0&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=

    var api = 'mtop.taobao.rate.detail';
    var version = '4.0';
    var params = {
        "api" : api,
        'v' : version,
        'ecode' : 0,
        'AntiCreep' : true,
        "data" :{"feedId":"1015159178791","isEncode":"true"}
    };
    var cookiePath = 'cookieV2.txt';
    return new Promise((resolve, reject)=> {
         taobaoToken(params ,cookiePath, function (body, err) {
             console.log(body, err)
            if(err){
               return  reject(err.message)
            }

            return body.data.list;
        })
    })
}

//是否有问答
function getAsk (itemId) {
    var api = 'mtop.taobao.social.feed.aggregate';
    var version = '1.0';
    var params = {
        "api" : api,
        'v' : version,
        'ecode' : '0',
        "timeout" : 300000,
        "timer" : 300000,
        "data" :{"pageId":28701,"env":1,"bizVersion":0,"params": JSON.stringify(
                {"refId": itemId, "namespace":1, "word":"磨","pageNum":1,"pageSize":3}
            )
        }
    };
    console.log(params)
    var cookiePath = 'cookieV2.txt';
    return new Promise((resolve, reject)=> {
        taobaoToken(params ,cookiePath, function (body, err) {
            console.log(body, err)
            if(err){
                return  reject(err.message)
            }

            return body.data.list;
        })
    })
}

var keywordsSearch =  function () {
    if (keywords = keywordsArr.shift()) {
        console.log(keywords);
        redisClient.SISMEMBER(redisKey, keywords, async function (err, result) {
            if (err) {
                return  console.log(err.message)
            }
            if (result) {
                return keywordsSearch();
            }

            await browserStart(keywords);
        });
    } else {
        console.log('end');
    }
}
keywordsSearch();

//getSHihuoAsk();

    //console.log(data)
    // if (data.taobaoUrls) {
    //     var taobaoUrls = data.taobaoUrls;
    //     var taobaoUrl = taobaoUrls.shift();
    //     var urlInfo = url.parse(taobaoUrl, true);
    //     list = await getAsk(urlInfo.query.id);
    //     console.log(list)
    // }

